# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Python application
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Qt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libegl1 \
          libxkbcommon-x11-0 \
          libxcb-icccm4 \
          libxcb-image0 \
          libxcb-keysyms1 \
          libxcb-randr0 \
          libxcb-render-util0 \
          libxcb-xinerama0
    - name: Lint with ruff
      run: |
        python3 -m ruff check .
    - name: Test with pytest  
      run: |  
        coverage run -m pytest -v
    - name: Generate Coverage Report  
      run: |  
        coverage report -m
